ClothBazaar.Web/Controllers/ProductController.cs
using ClothBazar.Services;
using ClothBazar.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClothBazar.Database;

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using ClothBazar.Services;

namespace ClothBazaar.Web.Controllers
{
          public class ProductController : Controller
          {
                    ProductsServices products = new ProductsServices();
                    // GET: Product
                    public ActionResult Index()
                    {
                              return View();
                    }

                    public ActionResult ProductTable(string search)
                    {
                            var product = products.GetProducts().ToList();
                              if (string.IsNullOrEmpty(search) == false)
                              {
                                        product = product.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
                              }
                              return PartialView(product);
                    }
                    
                    [HttpGet]
                    public ActionResult Create()
                    {
                              return View();
                    }

                    [HttpPost]
                    public ActionResult Create(Product product)
                    {
                              products.SaveProduct(product);
                              return RedirectToAction("ProductTable");
                    }

                    //[HttpGet]
                    //public ActionResult DeleteP(int ID)
                    //{
                    //          var productID = products.GetProduct(ID);
                    //          return View(productID);
                    //}

                    [HttpPost]
                    public ActionResult Delete(int ID)
                    {
                              //category = categoryServices.GetCategory(category.ID);
                              products.DeleteProduct(ID);
                              return RedirectToAction("ProductTable");
                    }

                    [HttpGet]
                    public ActionResult Edit(int Id)
                    {
                              var fetch = products.GetProduct(Id);
                              return View(fetch);
                    }

                    [HttpPost]
                    public ActionResult Edit(Product product)
                    {
                              products.UpdateProduct(product);
                              return RedirectToAction("ProductTable");
                    }
          }
}

ClothBazaar.Web/Views/Product/Create.cshtml
@{
    ViewBag.Title = "Create";
}
    <h2>Create</h2>
    <form id="createProduct" method="post">
        <h3>Name</h3>
        <input name="Name" />
        <br />
        <h3>Description</h3>
        <input name="Description" />
        <br />
        <h3>Price</h3>
        <input name="Price" />
        <br />
        <br />
        <button id="save" type="button">Save</button>
    </form>
<script>
    $("#save").click(function () {
        $.ajax({
            type: 'Post',
            url: '/Product/Create',
            data: $("#createProduct").serialize(),
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#addNew").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    })
</script>

ClothBazaar.Web/Views/Product/Edit.cshtml
@model ClothBazar.Entities.Product
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


<form id="ediitProduct" method="post">
    <input name="ID" value="@Model.ID" type="hidden" />
    <h3>Name</h3>
    <input name="Name" value="@Model.Name" />
    <br />
    <h3>Description</h3>
    <input name="Description" value="@Model.Description" />
    <br />
    <h3>Price</h3>
    <input name="Price" value="@Model.Price" />
    <br />
    <br />
    <button id="update" type="button">Update</button>
</form>

<script>
    $("#update").click(function () {
        $.ajax({
            type: 'Post',
            url: '/Product/Edit',
            data: $("#ediitProduct").serialize(),
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#editProduct").html("");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });
    });
</script>

ClothBazaar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div >
    @{
        Html.RenderAction("ProductTable");
    }
</div>

<div id="addNew">

</div>

<div id="editProduct">

</div>

ClothBazaar.Web/Views/Product/ProductTable.cshtml
@model List<ClothBazar.Entities.Product>
@{
    ViewBag.Title = "ProductTable";
}

@Scripts.Render("~/bundles/jquery")

<div id="tableContainer">

    <div>
        <h2>ProductTable</h2>
        <form method="post">
            <input id="searchInput" name="Search" />
            <button type="button" id="search">Search</button>
        </form>
        <button type="button" id="newBtn">New</button>
    </div>

    <div>
        <table>
            <thead>
                <tr>
                    <td>Products Name</td>
                    <td>Category</td>
                    <td>Price</td>
                    <td>Acrions</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var data in Model)
                 {
                          @*<input id="ID" name="ID" type="hidden" value="@data.ID"/>*@
                    <tr>
                        <td>@data.Name</td>
                        <td>-</td>
                        <td>@data.Price</td>
                        <td>
                            <button type="button" class="editbtn" pro-id="@data.ID">Edit</button>
                        </td>
                        <td>
                            <button class="deleteBtn" del-id="@data.ID">Delete</button>
                        </td>
                    </tr>
                 }
            </tbody>
        </table>
    </div>

</div>
<script>

    $("#search").click(function () {

        var searchVal = $("#searchInput").val();


        $.ajax({
            type: 'Post',
            url: '/Product/ProductTable',
            data: { search: searchVal }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

                alert("Fail");
            });

    })


    @*$(".deleteBtn").click(function ()
    {

		swal({
			title: "Confirm?",
			text: "Are you sure you want to delete this product?",
			icon: "warning",
			buttons: true,
			dangerMode: true,
		})
		.then((willDelete) => {
			if (willDelete) {
				$.ajax({
					type: 'POST',
					url: '@Url.Action("Delete", "Product")',
					data: {
						ID: $(this).attr('data-id')
					}
				})
				.done(function (response) {
					$("#tableContiner").html(response);

					swal("Record deleted Successfully.", {
						icon: "success",
					});
				})
				.fail(function (XMLHttpRequest, textStatus, errorThrown) {
					alert("FAIL");
				});

			}
            });
    });*@

    $(".deleteBtn").click(function () {

        var confirmDelete = confirm("Are you sure you want to delete this item?");

        if (confirmDelete)
        {
            $.ajax({
                type: 'Post',
                url: '/Product/Delete',
                data: { ID: $(this).attr('del-id') }
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                })

                .fail(function (XMLHttpRequest, textStatus, errorThrown) {

                    alert("Fail");
                });

        }
    });

    $("#newBtn").click(function () {

        //var searchVal = $("#searchInput").val();


        $.ajax({
            type: 'Get',
            url: '/Product/Create',
        })
            .done(function (response) {
                $("#addNew").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

                alert("Fail");
            });

    })

    $(".editbtn").click(function () {
        $.ajax({
            type: 'Get',
            url: '/Product/Edit',
            data: { Id: $(this).attr('pro-id'), }
        })
            .done(function (response) {
                $("#editProduct").html(response);
            })

            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

                alert("Fail");
            });

    });

</script>